version: '2'

services:  
    myproject:
        image: nantipat123/myproject:1.0.0
        container_name: myproject
        restart: always
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/src
        ports:
            - "8000:8000"